site_name: Laxmi Kant
site_description: Senior Android Developer portfolio for Laxmi Kant Pal in Gurugram, India.
site_author: lkant8
site_url: https://lkant8.github.io/
repo_url: https://github.com/lkant8/lkant8.github.io
repo_name: lkant8/lkant8.github.io
edit_uri: edit/master/docs/
use_directory_urls: true

theme:
  name: material
  language: en
  custom_dir: theme/overrides
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - toc.follow

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lkant8
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lkant/
      name: LinkedIn
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@alwayslaxmikant
      name: YouTube
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/alwayslaxmikant
      name: X

nav:
  - Home: index.md
  - DSA:
      - Factorial: dsa/factorial.md
  - Kotlin: kotlin.md
  - Android:
    - android/index.md
    - OnBaack Press: android/onbackpress.md
  - Portfolio:
    - portfolio/index.md
    - About: portfolio/about.md
    - Projects: portfolio/projects.md
  - Blogs: blogs.md

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css

copyright: Copyright &copy; 2026 Laxmi Kant Pal
