site_name: laxmikant.dev
site_description: DSA + App Development + YouTube Code
site_author: Laxmi Kant

repo_url: https://github.com/lkant8/lkant8.github.io
edit_uri: edit/master/docs/

theme:
  name: material
  language: en
  custom_dir: theme/overrides

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo

  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.tabs.link

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Home: index.md

  - DSA:
      - Factorial: dsa/factorial.md
  - Kotlin: kotlin.md
  - Android: android.md
  - Portfolio: portfolio.md
  - Blogs: blogs.md
